services:
  mcos-shell:
    image: ghcr.io/ernestofgaia/mcos-shell:latest
    container_name: mcos-shell
    restart: unless-stopped
    ports:
      - "8080:3000"
      - "4111:4111"
    env_file:
      - .env
    networks:
      - nginx-proxy

  mcos-postcards:
    image: ghcr.io/ernestofgaia/mcos-postcards:latest
    container_name: mcos-postcards
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./apps/postcards/.env
    networks:
      - nginx-proxy

  mcos-ochi:
    image: ghcr.io/ernestofgaia/mcos-ochi:latest
    container_name: mcos-ochi
    restart: unless-stopped
    ports:
      - "3003:3003"
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
